apiVersion: v1
kind: Service
metadata:
  labels:
    app: techrends
  name: techrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techrends
  type: ClusterIP
