apiVersion: v1
kind: Service
metadata:
  labels:
    app: techrends
  name: techrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: { .Values.service.targetPort }
  selector:
    app: techrends
  type: { .Values.service.type }
